#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 1000

#define FPS 60
#define FRAME_TARGET_TIME (1000 / FPS)

#define BLOCK_WIDTH 35
#define FIELD_ROWS 20
#define FIELD_COLUMNS 10
#define FIELD_WIDTH (BLOCK_WIDTH * FIELD_COLUMNS)
#define FIELD_HEIGHT (BLOCK_WIDTH * FIELD_ROWS)
#define FIELD_ORIGIN_X ((WINDOW_WIDTH - FIELD_WIDTH) / 4)
#define FIELD_ORIGIN_Y ((WINDOW_HEIGHT - FIELD_HEIGHT) / 2)

#define PREVIEW_WIDTH 6 * BLOCK_WIDTH
#define PREVIEW_HEIGHT 6 * BLOCK_WIDTH
#define PREVIEW_ORIGIN_X (FIELD_ORIGIN_X + FIELD_WIDTH + BLOCK_WIDTH)
#define PREVIEW_ORIGIN_Y ((FIELD_ORIGIN_Y + FIELD_HEIGHT) - PREVIEW_WIDTH)

#define CAP_FRAME_RATE TRUE
#define SHOW_GHOST TRUE
#define GRAVITY_TICK_INTERVAL_MS 500
