#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 1000

#define FPS 60
#define FRAME_TARGET_TIME (1000 / FPS)

#define BLOCK_WIDTH 40
#define FIELD_ROWS 20
#define FIELD_COLUMNS 10
#define FIELD_WIDTH (BLOCK_WIDTH * FIELD_COLUMNS)
#define FIELD_HEIGHT (BLOCK_WIDTH * FIELD_ROWS)
#define FIELD_ORIGIN_X ((WINDOW_WIDTH - FIELD_WIDTH) / 2)
#define FIELD_ORIGIN_Y ((WINDOW_HEIGHT - FIELD_HEIGHT) / 2)
